spring.application.name=fishExam
spring.datasource.url=jdbc:postgresql://localhost:32768/db
spring.datasource.username=rootuser
spring.datasource.password=rootpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.sql.init.mode=always
spring.sql.init.platform=postgres

gigachat.client.id=a1354d0a-6464-448c-87d5-c4b65ec12183
gigachat.client.secret=d4121d7c-9a53-4c9f-ab02-89ee6be68103
gigachat.auth.url=https://developers.sber.ru/api/auth/token
gigachat.api.url=https://developers.sber.ru/api/gigachat/v1
gigachat.client.authUrl=https://ngw.devices.sberbank.ru:9443/api/v2/oauth
gigachat.client.rqUid=26bb413d-ea81-4856-8fb3-6ec25ae3f0d1
